const en = {
  office: 'Live feed',
  offices: 'Offices',
  allOffices: 'All offices',
  agents: 'Agents',
  tasks: 'Messages',
  terminal: 'History',
  files: 'Files',
  projects: 'Rooms',
  roomActive: 'Active',
  roomInactive: 'Inactive',
  noActiveRooms: 'No active room at the moment.',
  discoveryNote:
    'New activity also brings older sessions into this view. Only a limited record window is loaded.',
  allSessions: 'All sessions',
  projectSearch: 'Search projects or sessions…',
  moreSessions: 'Show more',
  git: 'Data coverage',
  deploy: 'Deploy',
  analytics: 'Analytics',
  replay: 'Replay',
  settings: 'Settings',
  activity: 'Live activity',
  stats: 'Observed activity',
  allAgents: 'All agents',
  main: 'Main Codex',
  subagent: 'Agent',
  preview: 'Unassigned desk',
  previewNote: 'This character has no linked subagent in this session.',
  current: 'Observed state',
  stale: 'Last known state',
  offline: 'Source disconnected',
  unavailable: 'Record unavailable',
  paused: 'View paused',
  connecting: 'Connecting',
  connected: 'Connected',
  disconnected: 'Reconnecting',
  selectSession: 'Choose a session',
  search: 'Search projects or session IDs',
  noSessions: 'No main session found.',
  noMatch: 'No matching session.',
  allSources: 'All sources',
  desktop: 'Desktop',
  cli: 'CLI',
  unknown: 'Unknown',
  noEvents: 'No observed activity yet.',
  events: 'Events',
  tools: 'Tool calls',
  turns: 'Turns',
  team: 'Team',
  results: 'Tool results',
  readWindow: 'Counts cover the record window.',
  fileNote: 'This source does not provide a verified file list or diff.',
  notMeasured: 'Not measured',
  source: 'Source',
  updated: 'Last event',
  scope: 'Data coverage',
  detail: 'Session details',
  close: 'Close',
  observedTask: 'Observed work',
  noTask: 'No public task description is available in this record.',
  noTool: 'No tool event yet',
  working: 'Working',
  idle: 'Turn ended',
  waiting: 'Awaiting your reply',
  interrupted: 'Interrupted',
  unknownState: 'Unknown',
  pause: 'Pause view',
  resume: 'Resume view',
  openEvents: 'Open event history',
  session: 'Session',
  record: 'Record',
  partial: 'Partial history',
  partialNote: 'Older events may be outside the loaded window.',
  readOnly: 'Read only',
  sourceMissing: 'Codex session folder was not found.',
  scanError: 'The source could not be read. Last known data is retained.',
  staticView: 'Fixed camera',
  unlinked: 'No linked session',
  labels: 'Agent information cards',
  screens: 'Screen content',
  showCharacters: 'Characters',
  appearance: 'Office lighting',
  day: 'Daylight',
  dawn: 'Dawn',
  sceneLoading: 'Preparing the office view…',
  sceneError: 'This view could not load. Sunset remains available.',
  noLocation: 'Choose a city to follow the sun automatically.',
  chooseLocation: 'Choose city',
  changeLocation: 'Change city',
  sunset: 'Sunset',
  night: 'Night',
  appearanceHelp: 'Applies to all rooms and stays selected when you return.',
  nightLoading: 'Preparing the night view…',
  nightError: 'The night view could not load. Sunset remains available.',
  language: 'Language',
  automatic: 'Automatic',
  languageHelp:
    'Automatic follows the selected session’s language, then your browser preferences. Turkish and English are supported.',
  future: 'Not available in this observation view',
  wallTitle: 'MAIN CODEX / OBSERVED',
  monitorTitle: 'Activity',
  scopeNote:
    'Tool inputs, raw command output, file diffs and CPU usage are not available in this source.',
  layerTitle: 'Visual layers',
  layerNote:
    'Static room, character cutouts, foreground and screens share one fixed coordinate space.',
  assetError: 'The office image could not load. Session details are still available.',
  retry: 'Retry',
  viewSource: 'Source frame',
  cameraNote: 'The room is shown from one fixed angle.',
  status: 'Status',
  noLive: 'Waiting for a record',
  moreAgents: 'More agents in this room',
  taskNote: 'The latest public assistant message is shown below; it may describe completed work.',
  checked: 'Source checked',
  legacy: '3D prototype',
  blender: 'Blender pilot',
  preferences: 'Appearance',
  emptyConsole: 'Observed tool events will appear here.',
} as const;
type Copy = { [K in keyof typeof en]: string };
const tr: Copy = {
  office: 'Canlı akış',
  offices: 'Ofisler',
  allOffices: 'Tüm ofisler',
  agents: 'Ajanlar',
  tasks: 'Mesajlar',
  terminal: 'Geçmiş',
  files: 'Dosyalar',
  projects: 'Odalar',
  roomActive: 'Aktif',
  roomInactive: 'Pasif',
  noActiveRooms: 'Şu anda aktif oda yok.',
  discoveryNote:
    'Eski oturumlar da yeniden etkinlik olduğunda bu görünüme alınır. Yalnızca sınırlı kayıt aralığı yüklenir.',
  allSessions: 'Tüm oturumlar',
  projectSearch: 'Proje veya oturum ara…',
  moreSessions: 'Daha fazla göster',
  git: 'Veri kapsamı',
  deploy: 'Yayınla',
  analytics: 'İstatistik',
  replay: 'Tekrar',
  settings: 'Ayarlar',
  activity: 'Canlı etkinlik',
  stats: 'Gözlenen etkinlik',
  allAgents: 'Tüm ajanlar',
  main: 'Ana Codex',
  subagent: 'Alt ajan',
  preview: 'Atanmamış masa',
  previewNote: 'Bu karaktere bu oturumda bağlı bir alt ajan yok.',
  current: 'Gözlenen durum',
  stale: 'Son bilinen durum',
  offline: 'Kaynak bağlantısı kesildi',
  unavailable: 'Kayıt erişilemiyor',
  paused: 'Görünüm duraklatıldı',
  connecting: 'Bağlanıyor',
  connected: 'Bağlı',
  disconnected: 'Yeniden bağlanıyor',
  selectSession: 'Oturum seç',
  search: 'Proje veya oturum kimliği ara',
  noSessions: 'Ana oturum bulunamadı.',
  noMatch: 'Eşleşen oturum yok.',
  allSources: 'Tüm kaynaklar',
  desktop: 'Masaüstü',
  cli: 'CLI',
  unknown: 'Bilinmiyor',
  noEvents: 'Henüz gözlenen etkinlik yok.',
  events: 'Olaylar',
  tools: 'Araç çağrısı',
  turns: 'Tur',
  team: 'Ekip',
  results: 'Araç sonucu',
  readWindow: 'Sayaçlar okunan kayıt aralığına aittir.',
  fileNote: 'Bu kaynak doğrulanmış dosya listesi veya fark içeriği sağlamıyor.',
  notMeasured: 'Ölçülmedi',
  source: 'Kaynak',
  updated: 'Son olay',
  scope: 'Veri kapsamı',
  detail: 'Oturum ayrıntıları',
  close: 'Kapat',
  observedTask: 'Gözlenen iş',
  noTask: 'Bu kayıtta görünür bir görev açıklaması yok.',
  noTool: 'Henüz araç olayı yok',
  working: 'Çalışıyor',
  idle: 'Tur bitti',
  waiting: 'Cevap bekliyor',
  interrupted: 'Kesildi',
  unknownState: 'Bilinmiyor',
  pause: 'Görünümü duraklat',
  resume: 'Görünüme devam et',
  openEvents: 'Olay geçmişini aç',
  session: 'Oturum',
  record: 'Kayıt',
  partial: 'Kısmi geçmiş',
  partialNote: 'Eski olaylar yüklenen kayıt aralığının dışında olabilir.',
  readOnly: 'Salt okunur',
  sourceMissing: 'Codex oturum klasörü bulunamadı.',
  scanError: 'Kaynak okunamadı. Son bilinen veriler korunuyor.',
  staticView: 'Sabit kamera',
  unlinked: 'Bağlı oturum yok',
  labels: 'Ajan bilgi kartları',
  screens: 'Ekran içerikleri',
  showCharacters: 'Karakterler',
  appearance: 'Ofis ışığı',
  day: 'Gündüz',
  dawn: 'Şafak',
  sceneLoading: 'Ofis görünümü hazırlanıyor…',
  sceneError: 'Bu görünüm yüklenemedi. Gün batımı görünümü kullanılmaya devam ediyor.',
  noLocation: 'Işığın güneşi takip etmesi için şehir seç.',
  chooseLocation: 'Şehir seç',
  changeLocation: 'Şehri değiştir',
  sunset: 'Gün batımı',
  night: 'Gece',
  appearanceHelp: 'Tüm odalarda geçerlidir; bir sonraki ziyaretinde de korunur.',
  nightLoading: 'Gece görünümü hazırlanıyor…',
  nightError: 'Gece görünümü yüklenemedi. Gün batımı görünümü kullanılmaya devam ediyor.',
  language: 'Dil',
  automatic: 'Otomatik',
  languageHelp:
    'Otomatik seçim önce seçili oturumun dilini, ardından tarayıcı tercihlerini kullanır. Türkçe ve İngilizce desteklenir.',
  future: 'Bu gözlem görünümünde kullanılamıyor',
  wallTitle: 'ANA CODEX / GÖZLENEN',
  monitorTitle: 'Etkinlik',
  scopeNote: 'Araç girdileri, ham komut çıktısı, dosya farkları ve CPU kullanımı bu kaynakta yok.',
  layerTitle: 'Görsel katmanlar',
  layerNote:
    'Sabit oda, karakter kesitleri, ön parçalar ve ekranlar aynı sabit koordinatları kullanıyor.',
  assetError: 'Ofis görseli yüklenemedi. Oturum ayrıntılarına erişebilirsin.',
  retry: 'Yeniden dene',
  viewSource: 'Kaynak kare',
  cameraNote: 'Oda tek bir sabit açıdan gösteriliyor.',
  status: 'Durum',
  noLive: 'Kayıt bekleniyor',
  moreAgents: 'Odadaki diğer ajanlar',
  taskNote: 'Aşağıda son görünür asistan mesajı yer alır; tamamlanmış bir işi anlatıyor olabilir.',
  checked: 'Kaynak kontrolü',
  legacy: '3D prototip',
  blender: 'Blender denemesi',
  preferences: 'Görünüm',
  emptyConsole: 'Gözlenen araç olayları burada görünecek.',
};
export const fixedCopy = { en, tr };
export type OfficeCopy = Copy;
